name: Build runner image

on:
  push:
    paths:
      - Dockerfile
      - install-deps.sh

env:
  REGISTRY: ghcr.io

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/invakid404/abcccid-runner:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
