name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  scrape:
    runs-on: abcccid
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.19"

      - name: Scrape
        id: scrape
        run: |
          FIREFOX_BIN=/usr/bin/firefox \
          GECKODRIVER_BIN=/usr/bin/geckodriver \
            go run .

      - name: Check for existing tag
        uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: ${{ steps.scrape.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: ncipollo/release-action@v1
        if: ${{ steps.check-tag.outputs.exists == 'false' }}
        with:
          artifacts: ${{ steps.scrape.outputs.path }}
          artifactErrorsFailBuild: true
          tag: ${{ steps.scrape.outputs.version }}
